### ISSUE TITLE
error with use

### ISSUE THREAD

**Issue by kang2k10** [sanjivktr/PyQt5-Virtual-Keyboard#2]
Hello, i have some error
"virtual_keyboard_controller.py", line 288, in showAnimate
    self.move(self.x_pos, 2 * self.y_pos - self.y_pos * (val) / 25)
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'int'
  move(self, int, int): argument 2 has unexpected type 'float'

How fix this ?

**Comment by ahalama** [comment]
hi, int not working with delimeter.
old:
self.move(self.x_pos, 2 * self.y_pos - self.y_pos * (val) / 25)
new:
self.move(self.x_pos, round(2 * self.y_pos - self.y_pos * (val) / 25))

Good Luck
